export class Api{
  static token(){
    //reference token generated by rails - used for cross site referencing
    var tk = document.querySelector('meta[name="csrf-token"]');
    return tk ? tk.getAttribute('content') : '';
  }
  static headers(){
    //standard AJAX request structure
    return(
      {
        'Accept': 'application/json',
        'Content-type': 'application/json',
        'X-CSRF-Token': this.token(),
        'X-Requested-With': 'XMLHttpRequest'
      }
    )
  }
  //post - create new
  static post(route, params){
    return fetch(`${route}`, {
      method: 'post',
      dataType: 'JSON',
      credentials: 'include',
      header: this.headers()

    }, {body: JSON.stringify(params)});
  }

  //patch- update exisiting
  //get - retrieve
  //destroy -

}
