class AddStatsToCharacters < ActiveRecord::Migration[5.1]
  def change
    add_column :characters, :class1, :integer
    add_column :characters, :class2, :integer
    add_column :characters, :multiclass, :boolean
    add_column :characters, :alignment, :string
    add_column :characters, :initiative, :integer
    add_column :characters, :proficiencybonus, :integer
    add_column :characters, :inspiration, :integer
    add_column :characters, :ideals, :text
    add_column :characters, :bonds, :text
    add_column :characters, :flaws, :text
    add_column :characters, :attacks, :text
    add_column :characters, :spells, :text
    add_column :characters, :age, :integer
    add_column :characters, :height, :integer
    add_column :characters, :weight, :integer
    add_column :characters, :eyes, :string
    add_column :characters, :skin, :string
    add_column :characters, :hair, :string
    add_column :characters, :aliances, :text
    add_column :characters, :speed, :integer
    add_column :characters, :intel, :integer
    add_column :characters, :strength, :integer
    add_column :characters, :dexterity, :integer
    add_column :characters, :constitution, :integer
    add_column :characters, :wisdom, :integer
    add_column :characters, :agility, :integer
    add_column :characters, :charisma, :integer
    add_column :characters, :deathsavessuccess, :integer
    add_column :characters, :deathsavesfailures, :integer
    add_column :characters, :armorclass, :integer
    add_column :characters, :perception, :integer
    add_column :characters, :equipment, :text
    add_column :characters, :otherprofs, :integer
    add_column :characters, :animalhandle, :integer
    add_column :characters, :arcana, :integer
    add_column :characters, :athletics, :integer
    add_column :characters, :deception, :integer
    add_column :characters, :history, :integer
    add_column :characters, :insight, :integer
    add_column :characters, :intimidation, :integer
    add_column :characters, :investigation, :integer
    add_column :characters, :medicine, :integer
    add_column :characters, :nature, :integer
    add_column :characters, :performance, :integer
    add_column :characters, :persuasion, :integer
    add_column :characters, :religion, :integer
    add_column :characters, :slightofhand, :integer
    add_column :characters, :stealth, :integer
    add_column :characters, :survival, :integer
    add_column :characters, :factions, :text
    add_column :characters, :treasure, :text
    add_column :characters, :characterbackstory, :text
    add_column :characters, :features, :text
    add_column :characters, :additionalfeatures, :integer
  end
end
